### ISSUE TITLE
FIN_WAIT2状态请教

### ISSUE THREAD

**Issue by rangercyh** [soplwang/node-ka-patch#1]
朋友您好，我看过了你在node里的讨论：https://github.com/joyent/node/issues/3613，我遇到同样的问题，最后是如何解决的呢？这个patch是怎么使用的？

**Comment by soplwang** [comment]
直接 require 这个包即可。它是个 monkey-patch，自动启动 tcp keepalive。

发自我的 iPhone

**Comment by rangercyh** [comment]
我试过了，好像没效果，我现在的做法是把linux系统的keepalive时间从2小时改成60秒，然后再nodejs里面setKeepAlive(true)

**Comment by rangercyh** [comment]
cat /proc/sys/net/ipv4/tcp_keepalive_time  7200
cat /proc/sys/net/ipv4/tcp_keepalive_intvl  75
cat /proc/sys/net/ipv4/tcp_keepalive_probes  9
echo 60 > /proc/sys/net/ipv4/tcp_keepalive_time
echo 5 > /proc/sys/net/ipv4/tcp_keepalive_intvl
echo 3 > /proc/sys/net/ipv4/tcp_keepalive_probes

**Comment by soplwang** [comment]
我们生产环境是 0.8.x

发自我的 iPhone

**Comment by soplwang** [comment]
这是系统级参数，还需要应用程序里启用 keepalive 才生效。

发自我的 iPhone

**Comment by soplwang** [comment]
我这小补丁，就是为了不改各 node 库（如 socket.io），在关闭 socket 时启动 keepalive…

发自我的 iPhone

**Comment by rangercyh** [comment]
我明白的你的意思，如此我有两个问题：
1、net.setKeepAlive是否就是你所说的应用程序启动keepalive，我的代码是这样的：

```
var server = net.createServer(function (socket) {
    console.log('创建了一个新的socket连接：' + socket.remoteAddress + ' ' + socket.remotePort);
    var exBuffer = new ExBuffer();  
    exBuffer.on('data', function (buffer) {
        console.log('>> server receive data, length: ' + buffer.length);
        console.log(buffer.toString());
    });
    socket.on('data', function (data) {
        exBuffer.put(data); // 收到数据就往exbuffer里丢
    });
    socket.on('end', function () {
        console.log('客户端发来FIN，转CLOSE_WAIT，等写队列发完了，回发FIN转LAST_ACK');
        console.log('或者从FIN_WAIT2状态转TIME_WAIT状态，发ack');
    });
    socket.on('error', function (exception) {
        console.error('socket error and close socket：' + exception);
    });
    socket.on('close', function () {
        console.log('socket该销毁了：');
        socket.destroy();
    });
    socket.setKeepAlive(true);
    socket.setNoDelay(true);    // 去掉nagle算法
});
```

这么写，没有npm安装你的库，那个socket.setKeepAlive是不是效果跟你所述的一样呢？
2、如果上述效果不一样，我用npm安装了你的库，在我的程序里该怎么引用呢？之前我是这么写的，不过好像没有效果：

```
require('node-ka-patch');
    var server = net.createServer(function (socket) {
    socket.setNoDelay(true);    // 去掉nagle算法
});
```

求指导：）

**Comment by soplwang** [comment]
你自己设置了 setKeepalive 就好了啊 ^_^

发自我的 iPhone

**Comment by rangercyh** [comment]
明白了，谢谢！
