### ISSUE TITLE
使用这个patch，相关的系统参数是否需要修改呢？

### ISSUE THREAD

**Issue by code-sheng** [soplwang/node-ka-patch#2]
你好，请教一下，两个问题：
1、是否在 app.js里面 require 即可？
2、那些系统参数是否还需要进行修改？比如tcp_keepalive_time 这些，是否还是需要根据我们需要调整？

**Comment by soplwang** [comment]
1. 是的，是个全局的 monkey patch；
2. 不需要，做这个 runtime monkey patch 就是为了避免修改整个系统的全局参数（担心对其他应用产生不兼容问题）。
